### ISSUE TITLE
need a logo for birdhouse :)

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/birdhouse-docs#1]
nice and simple ...

**Comment by huard** [comment]
Email sent to Christina Germano (CANARIE) for help.

**Comment by cehbrecht** [comment]
We have a logo now thanks to David and Cristina :)

I have added to the logos folder:
https://github.com/bird-house/birdhouse-docs/tree/master/logos

I need to convert to `.png` and add it to the birdhouse documentation.

**Comment by huard** [comment]
Conversion to png done, but you can use the svg directly. I pushed the required change in conf.py but commented it. We may want to tweak the size.

**Comment by cehbrecht** [comment]
I have converted the logo to different sizes (64x64, 128x128) as png and added also a favicon.ico (32x32). Configured it in the `conf.py` ... works locally ... but the logo is not shown on RTD, only the favicon.ico. 

I fix this when I will clean up the docs #19.
