### ISSUE TITLE
include bibtex for references

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/birdhouse-docs#18]
https://sphinxcontrib-bibtex.readthedocs.io/en/latest/quickstart.html#minimal-example

**Comment by cehbrecht** [comment]
bibtex references could be part of the appendix:
https://github.com/bird-house/birdhouse-docs/blob/master/docs/source/appendix.rst

**Comment by huard** [comment]
At the office we use Mendeley to manage citations. It can export to bibtex. 
We could use it to collectively manage the bibtex file for the docs and the paper on overleaf (which can pull the bibtex from Mendeley). 
I created a birdhouse group : https://www.mendeley.com/community/birdhouse/
You should be able to join and add documents, then export to bibtex.

**Comment by nilshempelmann** [comment]
Quite fragile. 
extensions = [  'sphinxcontrib.bibtex', ] fails on github for the readthedocs 

not all bibtex syntax is recognized. currently just a test refs.bib file is includes with just a few entries

**Comment by nilshempelmann** [comment]
include Reference section 
https://birdhouse.readthedocs.io/en/latest/literature.html#id3

**Comment by nilshempelmann** [comment]
@cehbrecht @huard I propose to include birdhouse related citations in the presentations/publication section 
https://birdhouse.readthedocs.io/en/latest/publications.html# 

 and skip the general references (with mendeley?) since it is work to keep it up to date...

**Comment by nilshempelmann** [comment]
included.
