### ISSUE TITLE
projects-using-birdhouse

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/birdhouse-docs#30]
Good place to promote your projects. 

Currently just placeholders: 
https://birdhouse.readthedocs.io/en/latest/projects.html#projects-using-birdhouse

**Comment by huard** [comment]
Note that link to A2C2 is wrong: 
`.. _A2C2: https://a2c2.lsce.ipsl.fr/Atmospheric flow Analogues for Climate Change"`

**Comment by nilshempelmann** [comment]
Project section moved to [architecture examples ](https://birdhouse.readthedocs.io/en/latest/projects.html)

Content focussing on birdhouse framework technical aspects, from there the project documentation should be linked in with project specific information
