### ISSUE TITLE
Development Guide (Good practice for error handling) 

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/birdhouse-docs#32]
include some examples of how to handle log infromation

https://birdhouse.readthedocs.io/en/latest/dev_guide.html#writing-functions

**Comment by nilshempelmann** [comment]
@stephank16 
Here we can include a section about "Version indicators"

Something like:

- Full version (v1.0) with scientific publication in a reviewed journal
- subversion v.1.1  by major changes 
- subsub verions v.1.1.1 by minor changes
- patch v1.1.1_patch1 bugfix

**Comment by cehbrecht** [comment]
@nilshempelmann looks good :)
