### ISSUE TITLE
Update architecture section

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/birdhouse-docs#40]
- include new WPS e.g. pelican
- Extend functionallity description
- update/ add graphics

**Comment by huard** [comment]
A general question is how do we bring together birdhouse-docs and pavics-sdi ? pavics-sdi should be a superset of birdhouse-docs, adding elements of information specific to a given deployment.

**Comment by Zeitsperre** [comment]
It certainly isn't. I know we haven't moved too much within the Bird-house documentation but we have identified a few sphinx extension technologies that can help in linking the documentations of various birds. We have it employed on a few PAVICS services. I'll link the software here once I find it.

**Comment by nilshempelmann** [comment]
related to https://github.com/bird-house/birdhouse-docs/issues/38

**Comment by huard** [comment]
@Zeitsperre Are you referring to ReadTheDocs subprojects ?

**Comment by Zeitsperre** [comment]
@huard yes.

**Comment by nilshempelmann** [comment]
former architecture is now the [birdhouse-framwork](https://birdhouse.readthedocs.io/en/latest/framework.html) and updated. 

former project section are going to be [architecture-examples](https://birdhouse.readthedocs.io/en/latest/projects.html) 

To be further improved!
