### ISSUE TITLE
Update birdhouse framework graphic

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/birdhouse-docs#45]
Include pelican

**Comment by nilshempelmann** [comment]
Done: 
https://birdhouse.readthedocs.io/en/latest/framework.html#framework-structure

**Comment by nilshempelmann** [comment]
merge magic toolbox and ESMValTool WPS boxes, since it is one.
add 'Other archives'  (climate or non-climate data).

**Comment by nilshempelmann** [comment]
Also Label raven with same colour as the other birds, since it is build with cookiecutter as well.

**Comment by fmigneault** [comment]
[pelican](https://github.com/bird-house/pelican) is incorrectly written as `pelikan` in the graphic

**Comment by nilshempelmann** [comment]
@fmigneault Thanks for the observation. 
Graphic is updated including also the other points

**Comment by nilshempelmann** [comment]
done
