### ISSUE TITLE
General principles in guidelines 

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/birdhouse-docs#50]
Adding a section for general data handling advice like FAIR principles.

**Comment by nilshempelmann** [comment]
@cehbrecht Guidelines are also related to: https://github.com/bird-house/birdhouse-docs/issues/36
Whats needed here?

**Comment by cehbrecht** [comment]
> @cehbrecht Guidelines are also related to: #36
> Whats needed here?

The cookiecutter has already something for this topic in the dev guide:
https://github.com/bird-house/cookiecutter-birdhouse/blob/master/%7B%7Bcookiecutter.project_repo_name%7D%7D/docs/source/dev_guide.rst#prepare-a-release

I would keep it there ... it is more likely this section gets updated.

**Comment by nilshempelmann** [comment]
@cehbrecht OK. So we make jsut a link into the birdhouse-doc and have the same info at both places.
